# Generated by Django 5.2.5 on 2025-12-16 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_duration_alter_courselesson_duration'),
        ('headless_courses', '0001_initial'),
        ('students', '0002_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollments',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
    ]
