# Generated by Django 5.2.5 on 2025-09-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courselesson_media_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='duration',
            new_name='minutes',
        ),
        migrations.RenameField(
            model_name='courselesson',
            old_name='duration',
            new_name='minutes',
        ),
        migrations.RenameField(
            model_name='historicalcourse',
            old_name='duration',
            new_name='minutes',
        ),
        migrations.RenameField(
            model_name='historicalcourselesson',
            old_name='duration',
            new_name='minutes',
        ),
    ]
