# Generated by Django 5.2.5 on 2025-09-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_duration_course_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='minutes',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='courselesson',
            old_name='minutes',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='historicalcourse',
            old_name='minutes',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='historicalcourselesson',
            old_name='minutes',
            new_name='duration',
        ),
    ]
