# Generated by Django 5.2.5 on 2025-10-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_duration_alter_courselesson_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselesson',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='historicalcourselesson',
            name='thumbnail',
        ),
    ]
