# Generated by Django 5.2.5 on 2025-10-03 13:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_courselesson_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcourselesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicalcourselesson',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalcourselesson',
            name='history_user',
        ),
        migrations.AddField(
            model_name='courselesson',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='related_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=20)),
                ('file_key', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.courselesson')),
            ],
            options={
                'verbose_name_plural': 'Course Lesson Resources',
                'db_table': 'course_lesson_resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='HistoricalCourse',
        ),
        migrations.DeleteModel(
            name='HistoricalCourseLesson',
        ),
    ]
