# Generated by Django 5.2.5 on 2025-10-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_lessonresource_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courselesson',
            unique_together={('course', 'title')},
        ),
    ]
