# Generated by Django 5.2.5 on 2025-10-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_courselesson_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresource',
            name='file_type',
            field=models.CharField(max_length=128),
        ),
    ]
