# Generated by Django 5.2.5 on 2025-10-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_lessonresource_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
