# Generated by Django 5.2.5 on 2025-10-04 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0007_remove_historicalinstructorprofile_history_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('scope', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('read_write', 'Read & Write')], default='read', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor Key',
                'verbose_name_plural': 'Instructor Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instructor', 'is_active'], name='instructors_instruc_603e45_idx')],
            },
        ),
    ]
