# Generated by Django 5.2.5 on 2025-09-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_instructor_created_at_instructor_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
