# Generated by Django 5.2.5 on 2025-09-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0005_alter_historicalinstructor_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstructor',
            name='profile_completion_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('partial', 'Partial')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='instructor',
            name='profile_completion_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('partial', 'Partial')], default='pending', max_length=20),
        ),
    ]
