# Generated by Django 5.2.5 on 2025-10-30 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0010_alter_instructorprofile_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='instructor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
