class HEADLESS_ERR_CODES:
    DATA_CONSISTENCY_ERR = "DATA_CONSISTENCY_ERR"

    VALIDATION_ERR = "VALIDATION_ERR"

    API_KEY_ERR = "API_KEY_ERR"
    INVALID_EXPIRED_TOKEN_ERR = "INVALID_EXPIRED_TOKEN_ERR"

    LIST_FETCH_ERR = "LIST_FETCH_ERR"
    RETRIEVAL_ERR = "RETRIEVAL_ERR"

    INTERNAL_ERR = "INTERNAL_ERR"