services:
  # Redis
  redis:
    image: redis:7-alpine
    container_name: jiroshi_redis_prod
    volumes:
      - redis_data:/data
    networks:
      - jiroshi_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Jiroshi Server (Django) 
  jiroshi_server:
    image: jiroshi_dashboard:latest
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.prod
    env_file:
      - ../.env.prod
    ports:
      - "8000:8000"
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application
        --bind 0.0.0.0:8001
        --workers 3
        --threads 2
      "
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - jiroshi_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/v1/dashboard/internals/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Worker
  celery:
    image: jiroshi_dashboard:latest
    command: celery -A config worker -l info --concurrency=2
    env_file:
      - ../.env.prod
    depends_on:
      jiroshi_server:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - jiroshi_network


volumes:
  redis_data:

networks:
  jiroshi_network:
    driver: bridge