class ERR_CODES:
    INTEGRITY_ERR = "INTEGRITY_ERR"
    VALIDATION_ERR = "VALIDATION_ERR"

    API_KEY_ERR = "API_KEY_ERR"
    INVALID_TOKEN_ERR = "INVALID_TOKEN_ERR"
    ACCESS_DENIED_ERR = "ACCESS_DENIED_ERR"

    ALREADY_EXISTS_ERR = "ALREADY_EXISTS_ERR"
    NOT_FOUND_ERR = "NOT_FOUND_ERR"

    INTERNAL_ERR = "INTERNAL_ERR"