class ERR_CODES:
    DATA_CONSISTENCY_ERR = "DATA_CONSISTENCY_ERR"
    INTEGRITY_ERR = "INTEGRITY_ERR"
    VALIDATION_ERR = "VALIDATION_ERR"

    API_KEY_ERR = "API_KEY_ERR"
    INVALID_TOKEN_ERR = "INVALID_TOKEN_ERR"

    ALREADY_EXISTS_ERR = "ALREADY_EXISTS_ERR"
    NOT_FOUND_ERR = "NOT_FOUND_ERR"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    LIST_FETCH_ERR = "LIST_FETCH_ERR"
    RETRIEVAL_ERR = "RETRIEVAL_ERR"

    INTERNAL_ERR = "INTERNAL_ERR"