# Generated by Django 5.2.5 on 2025-09-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_access_status_courselesson_access_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='media_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourselesson',
            name='media_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
