# Generated by Django 5.2.5 on 2025-10-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_course_duration_alter_courselesson_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='media_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='file_size',
            field=models.BigIntegerField(),
        ),
    ]
