# Generated by Django 5.2.5 on 2025-10-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_historicalinstructor_profile_completion_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinstructorprofile',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinstructorprofile',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='historicalinstructorsession',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinstructorsession',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='historicalloginattempt',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalloginattempt',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='HistoricalInstructor',
        ),
        migrations.DeleteModel(
            name='HistoricalInstructorProfile',
        ),
        migrations.DeleteModel(
            name='HistoricalInstructorSession',
        ),
        migrations.DeleteModel(
            name='HistoricalLoginAttempt',
        ),
    ]
