# Generated by Django 5.2.5 on 2025-10-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0008_instructorkeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
