"""
Django settings for dashboard project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from dotenv import load_dotenv
import os
import structlog, logging
from pathlib import Path
from datetime import timedelta
from urllib.parse import urlparse, parse_qsl
from apps.core.logging import LOG_QUEUE

load_dotenv()


structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.processors.add_log_level,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.JSONRenderer(),
    ],
    wrapper_class=structlog.make_filtering_bound_logger(logging.INFO),
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.getenv('DJANGO_DEBUG', 'True'))

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

INSTALLED_MODULES = [
    "rest_framework_simplejwt.token_blacklist",
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'django_filters',
]

COMMONS_APPS = ['apps.core',]

DASHBOARD_APPS = [
    'apps.dashboard.instructors',
    'apps.dashboard.audit',
    'apps.dashboard.courses',
    'apps.dashboard.apikeys',
    'apps.dashboard.dashboard',
    'apps.dashboard.students'
]

HEADLESS_APPS = [
    'apps.headless.instructor',
    'apps.headless.students',
    'apps.headless.courses'
]

INSTALLED_APPS = DJANGO_APPS + INSTALLED_MODULES + COMMONS_APPS + DASHBOARD_APPS + HEADLESS_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    # Custom middleware for comprehensive logging
]

if not DEBUG:
    MIDDLEWARE += [
        'apps.core.middleware.APILoggingMiddleware',
        'apps.core.middleware.SecurityHeadersMiddleware',
        # 'apps.core.middleware.RateLimitMiddleware',
    ]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME'),
#         'USER': os.getenv('DB_USER'),
#         'PASSWORD': os.getenv('DB_PASSWORD'),
#         'HOST': os.getenv('DB_HOST', "localhost"),
#         'PORT': os.getenv('DB_PORT', "5432"),
#     }
# }

tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': tmpPostgres.path.replace('/', ''),
        'USER': tmpPostgres.username,
        'PASSWORD': tmpPostgres.password,
        'HOST': tmpPostgres.hostname,
        'PORT': 5432,
        'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('INSTRUCTOR_ACCESS_TOKEN_EXP', 60))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('INSTRUCTOR_REFRESH_TOKEN_EXP', 7))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'SIGNING_KEY': SECRET_KEY
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "apps.core.throttles.dashboard_throttle.InstructorAuthBurstThrottle",
        "apps.core.throttles.dashboard_throttle.InstructorRateThrottle",
        "apps.core.throttles.headless_throttle.StudentAuthBurstThrottle",
        "apps.core.throttles.headless_throttle.StudentRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/min",
        "user": "1000/min",
        "instructor": "1000/min",
        "student": "300/min",
        "instructor_auth": "10/min",
        "student_auth": "10/min",
        "student_public": "200/min"
    },
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False, # Disable session-based auth for API docs
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'instructors.Instructor'

# Celery Settings
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'


# CORS SETTINGS
# For headless LMS - DYNAMIC configuration for any custom domain

# 1. Enable credentials (required for HTTP-only cookies)
CORS_ALLOW_CREDENTIALS = True

# 2. Allow ANY domain dynamically
# The trick: We can't use "Allow All = True" with credentials.
# Instead, we use a Regex that matches EVERYTHING.
# This tells Django to "reflect" the incoming Origin header back to the browser,
# which satisfies the browser's security check for credentials.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^.*$",  # Match any origin (http, https, localhost, capacitor, etc.)
]

# Note: We explicitly DO NOT set CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOWED_ORIGINS list is also not needed anymore as the regex covers everything.

# Allowed methods for API requests
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allowed headers (including custom API key header)
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-api-key',
    'x-csrftoken',
    'x-requested-with',
]

# Apply CORS only to headless API
CORS_URLS_REGEX = r"^/api/.*$"

# Cookie settings for cross-origin requests
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = not DEBUG  # True in production (HTTPS required)
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = not DEBUG  # True in production (HTTPS required)


# Mailer Settings
ADMINS = [("Jiroshi Alerts", "app.jiroshi@gmail.com")]

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "app.jiroshi@gmail.com"
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_APP_PASSWORD")


# Logging Config
from apps.core.logging import LOG_QUEUE

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "queue": {
            "class": "logging.handlers.QueueHandler",
            "queue": LOG_QUEUE,
            "level": "ERROR",
        },
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "jiroshi": {
            "handlers": ["console", "queue"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

