# Generated by Django 5.2.5 on 2025-11-06 08:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apikeys',
            unique_together={('instructor', 'key_name', 'key_type')},
        ),
    ]
