# Generated by Django 5.2.5 on 2025-09-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='access_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='access_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcourselesson',
            name='access_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
    ]
