# Generated by Django 5.2.5 on 2025-10-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_courselesson_media_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='duration',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
