# Generated by Django 5.2.5 on 2025-12-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0002_alter_apikeys_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikeys',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
    ]
